language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - 7

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist --prefer-stable --dev

script: vendor/bin/phpunit
